### ISSUE TITLE
Slug is not set to adapter

### ISSUE THREAD

**Issue by eduardhasanaj** [tweedegolf/storage-abstraction#11]
I am using this package and I have observed that slug is not set to adapter according to the value specified in config object.
Instead I set it manually after the storage is created.
This happens in GoogleCloudStorageAdapter.
```
let storage = new Storage(options);
storage.adapter.slug = false;
await storage.init();
```

**Comment by abudaan** [comment]
When I try to create a bucket with a space, like for instance "the buck", GCS complains that the bucketname is invalid.

**Comment by abudaan** [comment]
In version 1.4.5 the key `slug` has been removed from the config object: the responsibility for providing a valid bucket name has therefor shifted onto the programmer. I think this a more flexible approach.
