### ISSUE TITLE
Support for Azure? Minio?

### ISSUE THREAD

**Issue by drernie** [tweedegolf/storage-abstraction#30]
Very interesting!

Any idea how difficult it would be to support Azure clouds?

And do you already work with Minio?

**Comment by abudaan** [comment]
See [this PR](https://github.com/tweedegolf/storage-abstraction/pull/33) from @tesirm99 

I am finishing up a new version atm and will publish it in the coming days.

I think MinIO is S3 compatible so it should work with the `AdapterAmazonS3`. Though I haven't tested it myself yet.

**Comment by abudaan** [comment]
Azure is supported in the upcoming version 1.4.8

I have tested MinIO with `AdapterAmazonS3` but that doesn't work; I am working on a new adapter for MinIO, will be available in version 2.x

Version 2.x will be a complete overhaul of the API and I hope to be able to publish it by the end of this month (November 2023)

**Comment by abudaan** [comment]
The latest version is 1.5.2 and it has support for Azure.

Recently I have updated the Amazon adapter to v3 of the S3 API but unfortunately MinIO only supports the older S3 API so I have to write a separate adapter.

Btw: I didn't know MinIO before but I really it, thank you!
