### ISSUE TITLE
Is cloudflare R2 supported in S3 type?

### ISSUE THREAD

**Issue by rnbokade** [tweedegolf/storage-abstraction#37]

**Comment by abudaan** [comment]
It should work since the API is S3 compatible. Will write a test for R2.

**Comment by abudaan** [comment]
I have tested R2 and it works using the `AdapterAmazonS3`. 

There are some extra requirements for the config though:

- you have to set a value for `endpoint`.
- you can either leave `region` out or set it to on of these values: wnam, enam, weur, eeur, apac, auto

Will be available in the upcoming version 1.4.8
