### ISSUE TITLE
Release 1.4.7 on npm

### ISSUE THREAD

**Issue by rupurt** [tweedegolf/storage-abstraction#38]
Howdy :wave: 

The current latest release on npm is 1.4.6

https://www.npmjs.com/package/@tweedegolf/storage-abstraction?activeTab=versions

**Comment by ronak1009** [comment]
I too want to use 1.4.7 which supports azure blob storage. When Can I expect the package to be published on npm ?

**Comment by abudaan** [comment]
Version 1.4.7. has been published to npm
