### ISSUE TITLE
Google cloud storage adapter assumes create bucket IAM permissions

### ISSUE THREAD

**Issue by rupurt** [tweedegolf/storage-abstraction#42]
The GCS adapter assumes that the configured credentials have been granted the permissions to create buckets. This is often not true and results in most calls failing when put object is granted but create bucket is not

e.g. `init` https://github.com/tweedegolf/storage-abstraction/blob/master/src/AdapterGoogleCloudStorage.ts#L84

How do you feel about changing the adapter to accept an argument such as `assumeCreated: true` so that it can bypass bucket creation but still list files and put/delete objects?

**Comment by abudaan** [comment]
Yes good point! I am working on a complete overhaul of the API; the new init() method won't create a bucket automatically anymore. That said: if you do not supply a bucket name in the config init() won't call the createBucket() method.

**Comment by abudaan** [comment]
fixed in 1.4.7

**Comment by rupurt** [comment]
Awesome. Thank you!

**Comment by abudaan** [comment]
You're welcome! I had issues with publishing to npm to the latest version is 1.5.2
