### ISSUE TITLE
Module not found - @tweedegolf/storage-abstraction/dist/Storage.js:73:27

### ISSUE THREAD

**Issue by nkorent** [tweedegolf/storage-abstraction#47]
hey guys, I'm using nextjs 14 and I want to upload file to my local storage using this package but I can not move far.

Version I have installed is 1.5.2.

I'm using form actions, I do get the file there and the part with form works well. The part where I do have issue with is when I call the library with new Storage(config).

I'm trying to instantiate it as it's stated in readme:

...
`import { Storage, StorageType } from "@tweedegolf/storage-abstraction";`
...
```export const createFile = formAction(createFileSchema, async (data) => {
  console.log(data.file);
  console.log(data.folderId);

  const s = new Storage({
    type: StorageType.LOCAL,
    directory: "~/code/uploadtest",
    skipCheck: true,
  });

  console.log(s);

  // await documentService.createDocument(data);
  revalidatePath(route("admin.dataset.show", { id: data.folderId }));
  redirect(route("admin.dataset.show", { id: data.folderId }));
});
```
....

and the error I am getting is always the same:

<img width="973" alt="Screenshot 2023-12-04 at 17 56 40" src="https://github.com/tweedegolf/storage-abstraction/assets/32095650/a5eb910c-c1aa-48c6-92a2-fe02a93867dc">

I have tried installing aws-sdk as well, but that did not help at all too (was a far fetch anyways).

I am not sure how to proceed to even debug this issue in the package so any advice would be welcome.

**Comment by abudaan** [comment]
Thanks!
