### ISSUE TITLE
Why not making storage adapters peer dependencies?

### ISSUE THREAD

**Issue by ps73** [tweedegolf/storage-abstraction#50]
First thank you for this great library. I am using it in a prototype currently and I really enjoy the fact that I can quickly move from internal storage to s3 based storage.

I am thinking about why the storage adapter dependencies are not peer dependencies, because currently the backblaze-b2 package has a vulnerability because of one inside an older axios version which this package uses.

I have already [created a pull request inside the repo of backblaze-b2](https://github.com/yakovkhalinsky/backblaze-b2/pull/132) which got merged some weeks ago but was not released yet.

Imho the best would be if every storage adapter would be a peer dependency requiring the users to install the seperate package by their own when they want to use a specific storage adapter.
For me the benefit would be that this package does not need to update the dependencies every time when a patch or minor release without breaking change was released and on the other hand there won't be installed any useless package inside a project which only uses one explicit storage adapter.

**Comment by abudaan** [comment]
Thanks, great idea! 

I have already implemented it in version 2.0.0. which I hope to finalize and publish in the coming week.

**Comment by abudaan** [comment]
Interestingly enough, I originally had the idea to move the adapters in to their own packages. For some reason I left the idea, not sure why. I found some remains of the idea on NPM:

![image](https://github.com/tweedegolf/storage-abstraction/assets/299669/b0af1b9f-b5bb-4bb8-9b75-f2ba5ac3153d)

**Comment by ps73** [comment]
Hi @abudaan,
that sounds great!

I am so thankful for your great work. 🎉

**Comment by abudaan** [comment]
Version 2.0.0 has been published to NPM
