### ISSUE TITLE
AbstractAdapter validate bucketName option should be optional but isn't

### ISSUE THREAD

**Issue by ueberBrot** [tweedegolf/storage-abstraction#59]
For the `AdapterLocal` the `bucketName` is defined as optional in the `AdapterConfig` ([Link](https://github.com/tweedegolf/storage-abstraction/blob/796509ec4638bd9560d3e7329402c0b6fab7198f/src/types/general.ts#L22))

```ts
export interface AdapterConfig {
    bucketName?: string;
    [id: string]: any;
}
```

But it is actually required as it is shown in the `AbstractAdapter` file [here](https://github.com/tweedegolf/storage-abstraction/blob/796509ec4638bd9560d3e7329402c0b6fab7198f/src/AbstractAdapter.ts#L248).

**Comment by abudaan** [comment]
`bucketName` is not required upon instantiation but if you don't provide it in the config you must provide it as a param to `addFile`.

You can see it literally in the code:

```typescript
if (typeof params.bucketName === "undefined") {  // if bucketName is not provided to addFile
      if (this._bucketName === null) {           // and it hasn't been set upon instantiation
        return {                                 // we return an error
          value: null,
          error: "no bucket selected",
        };

```
