### ISSUE TITLE
Local Adapter File Writes Require bucketName

### ISSUE THREAD

**Issue by granthusbands** [tweedegolf/storage-abstraction#64]
I just had trouble writing files to local storage because bucketName is required (either on the writeFile or on the config object). Can it just not? I want to just write files into the given folder, not into a subfolder.

**Comment by abudaan** [comment]
Yes, that is done because of consistency; all cloud storage services require a bucket name.

If you want to store files directly in a local folder you can do this:

```typescript
  // config url
  const config = "local://./@folder";
  
  // config object
  const config = {
    type: StorageType.LOCAL,
    directory: "./",
    bucketName: "folder",
  };


```
