### ISSUE TITLE
Add license info (license.md)

### ISSUE THREAD

**Issue by rijkvanzanten** [tweedegolf/storage-abstraction#7]
Hi there!

I'm interested in using your project, however the lack of open source license means that I'm prohibited from doing so. 

I noticed you set the license field in `package.json`  to MIT, which indicates to me that you intend this project to be MIT licensed. Would you accept a PR to add a `LICENSE.md` file and add the license info to the readme?

Groetjes! ✌️

**Comment by abudaan** [comment]
Thanks for noticing and yes please, go ahead!
